#@ load("@ytt:data","data")
#@ load("@ytt:base64","base64")
---
#@ if data.values.clusters.prod_cluster.enabled:
profile: run
ceip_policy_disclosed: True
supply_chain: testing_scanning

cnrs:
  domain_name: #@ data.values.clusters.prod_cluster.ingressDomain
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: "kube-system/wildcard"

contour:
  envoy:
    service:
      type: #@ data.values.contour.serviceType
#@ if data.values.clusters.view_cluster.enabled:
appliveview_connector:
  backend:
    sslDisabled: "true"
    host: #@ "appliveview.{}".format(data.values.clusters.view_cluster.ingressDomain)
#@ end
shared:
  ingress_domain: #@ data.values.clusters.prod_cluster.ingressDomain
  ca_cert_data: #@ base64.decode(data.values.tls.certData)
#@ end

package_overlays:
- name: cnrs
  secrets:
  - name: cnrs-overlay