apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test     # (!) required
spec:
  params:
    - name: source-url                       # (!) required
    - name: source-revision                  # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: ghcr.io/vrabbi/gradle
            script: |-
              #!/bin/bash
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              if test -f "mvnw"; then
                ./mvnw test
              elif test -d "META-INF"; then
                jar cvfm0 test2.jar META-INF/MANIFEST.MF *
                nohup java -jar test2.jar > /dev/null 2>&1 &
                serverPID=$!
                sleep 10
                status_code=$(curl --write-out %{http_code} --silent --output /dev/null  http://localhost:8080)
                if [ "$status_code" -eq 200 ]; then
                  echo "Got 200 response from java app!"
                else
                  echo "Failed with Status Code $status_code"
                  exit 1
                fi
                kill $serverPID
              else
                echo No tests match this app. continuing on to scan.
              fi
